### ISSUE TITLE
Port to 1.12.2

### ISSUE THREAD

**Issue by lolwut2** [pleasegivesource/viewmodel-changer#4]
Could you port to 1.12.2, thanks.

**Comment by lolwut2** [comment]
Like port it to 1.12.2 forge if it's possible.

**Comment by REALERvolker1** [comment]
Are you trying to use it on an anarchy server? If so, use Kami Blue or literally any other client

**Comment by shockpast** [comment]
1) porting from fabric to forge is long process
2) old version
