### ISSUE TITLE
[bug] cannot open gui

### ISSUE THREAD

**Issue by goztb22** [pleasegivesource/viewmodel-changer#5]
Gui not oppening even if i press backslash but config created

**Comment by REALERvolker1** [comment]
what other mods do you have installed?

**Comment by goztb22** [comment]
Meteor

**Comment by goztb22** [comment]
I do not like meteor viewmodel thats why i would use that

**Comment by zarids** [comment]
did you ever get it

> 
> 
> I do not like meteor viewmodel thats why i would use that

**Comment by goztb22** [comment]
yesi dont really need
